app:
  name: MyApp
model:
  name: gemma4:26b
speech:
  user_input: False
log_file:
  name: example.log

server_urls:
  game_state_url: http://localhost:3000/post_game_state/
  whisper_url: http://hal9000.skim.th-owl.de:8003/transcribe
  ollama_url: http://hal9000.skim.th-owl.de:11437
