app:
  name: MyApp
model:
  name: gemma4:26b
  name: llama3.1:8b
  # name: mistral:7b
  # name: qwen2.5:7b
  name: qwen3:8b
  name: gpt-oss:20b
  # name: llama3.3:latest
  # name: qwen3.6:27b
  # name: glm-4.7-flash:q4_K_M
  # name: nemotron3:33b
  # name: gemma4:e4b
  name: nemotron-3-nano:4b
  # name: phi4-mini:latest
  # name: lfm2.5-thinking


scoring:
  type: normal
  # type: trajectory


speech:
  user_input: False
  audio_file: mic.wav
log_file:
  name: "example_test.log"

server_urls:
  game_state_url: http://localhost:3000/post_game_state/
  game_task_url: http://localhost:3000/set_game_task/
  whisper_url: http://hal9000.skim.th-owl.de:8003/transcribe
  # ollama_url: http://hal9000.skim.th-owl.de:11437
  ollama_url: http://hal9000.skim.th-owl.de:11430


